# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@agentclientprotocol/sdk-0.12.0" = {
      name = "_at_agentclientprotocol_slash_sdk";
      packageName = "@agentclientprotocol/sdk";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@agentclientprotocol/sdk/-/sdk-0.12.0.tgz";
        sha512 = "V8uH/KK1t7utqyJmTA7y7DzKu6+jKFIXM+ZVouz8E55j8Ej2RV42rEvPKn3/PpBJlliI5crcGk1qQhZ7VwaepA==";
      };
    };
    "zod-3.25.76" = {
      name = "zod";
      packageName = "zod";
      version = "3.25.76";
      src = fetchurl {
        url = "https://registry.npmjs.org/zod/-/zod-3.25.76.tgz";
        sha512 = "gzUt/qt81nXsFGKIFcC3YnfEAx5NkunCfnDlvuBSSFS02bcXu4Lmea0AFIUwbLWxWPx3d9p8S5QoaujKcNQxcQ==";
      };
    };
  };
in
{
  pi-acp = nodeEnv.buildNodePackage {
    name = "pi-acp";
    packageName = "pi-acp";
    version = "0.0.27";
    src = fetchurl {
      url = "https://registry.npmjs.org/pi-acp/-/pi-acp-0.0.27.tgz";
      sha512 = "uEqgqTOSfd+EuTqVlLAfHhY0OWcd5jgjXxLweNHuUoddRbhDcZCy7vgccC6z3Z+v7zcUxm2jXo66NyOHXt1tsQ==";
    };
    dependencies = [
      sources."@agentclientprotocol/sdk-0.12.0"
      sources."zod-3.25.76"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "ACP adapter for pi coding agent";
      homepage = "https://github.com/svkozak/pi-acp#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  chrome-devtools-mcp = nodeEnv.buildNodePackage {
    name = "chrome-devtools-mcp";
    packageName = "chrome-devtools-mcp";
    version = "1.1.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/chrome-devtools-mcp/-/chrome-devtools-mcp-1.1.1.tgz";
      sha512 = "Fs/ASXAkQqvYCbJjHIx/pnShjyIoZoPxdg4J3wjaA9FLkRb2ngGnisu2AGcBIXdw5qrPkOuV/cOlGOonpsE1qw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "MCP server for Chrome DevTools";
      homepage = "https://github.com/ChromeDevTools/chrome-devtools-mcp#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
